//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bliss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class questions_choices
    {
        public int questionID { get; set; }
        public int choiceID { get; set; }
        public int votes { get; set; }
    
        public virtual choices choices { get; set; }
        public virtual questions questions { get; set; }
    }
}
